# Generated by Django 4.0.2 on 2022-02-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='Category',
        ),
    ]
