# Generated by Django 4.0.2 on 2022-02-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_catalog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avialable',
            new_name='available',
        ),
    ]
