# Generated by Django 4.0.2 on 2022-02-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
